stages:
  - code_quality
  - test
  - deploy
  
image: python:3.6-alpine

before_script:
  - pip install pipenv==2018.11.26
  - pipenv install --system --deploy

validate_code:
  stage: code_quality
  script:
    - flake8